### ISSUE TITLE
Using sqlite3.cached leads to unfulfilled requests on non-existent databases

### ISSUE THREAD

**Issue by reyemtm** [tobinbradley/mbtiles-server#6]
As I have been working on yet another fork of the mbtiles-server project, I noticed a bug when using the `.cached` feature. On the initial attempt at reaching a non-existent tile layer, the function returns the [error](https://github.com/tobinbradley/mbtiles-server/blob/f8c96a36e862ec0de0e382eb932f52bc6e7c25f8/index.js#L66) as expected. However, since this connection is cached, further attempts will not throw any errors as the "connection" already exists. This leads to unfulfilled requests. I have attempted some workarounds but have not found a good solution yet other than not using a cached connection. It is possible to check for events in the db connection and then simply return a 404 if any are found, but it is possible to have random connection events on an otherwise health connection, so this method will not work. Looking for solutions...

**Comment by tobinbradley** [comment]
If I understand correctly, you're querying a mbtiles file that doesn't exist, and when that mbtiles file comes to exist at some future point in time, you're still getting an error because the db connection is cached via `sqlite.cached.Database(...)`. Is that the issue?

I don't think there's an elegant solution to this problem, other than not using the db caching function of the SQLite connection.  See [here](https://github.com/mapbox/node-sqlite3/issues/1277) - seems like it's describing the same problem (mbtiles too), and the short answer is no, just drop `.cached`.

But...lemme think on this a little more.

**Comment by tobinbradley** [comment]
OK. I had been meaning to update the sqlite library to [better-sqlite3](https://www.npmjs.com/package/better-sqlite3) for a while now, and I figured...YOLO. It's big features are (a) faster, (b) easier to use, and (c) *faster*. 

I've been running the new code in production for a bit and it seems solid. It's also seems to be using less RAM (not that the other version was a hog), and I was able to drop ~1/3 of the code (not that that was a hog either).

Feel free to give it a shot. As it isn't caching DB connections, it'll run fine with mbtiles files bouncing in and out, so you should be good, and the speed improvement should be > than the bump the sqlite cached database was achieving.

**Comment by reyemtm** [comment]
Well now that I have my fork of this running on our actual (old) server, it is fast, but not nearly as fast as the GO server (though probably fine for the average user). It's running on two processes and on initial connection load times can be upwards of > 1 sec per tile, but further requests are much faster. Still, it's in a language I can understand so there's that. It was loading faster running on my dev machine so upgrading our server would help.

#### GO vs Fastify vs AGOL Cache
https://www2.ci.lancaster.oh.us/wmts-server/preview/#10/39.7436/-82.5919

**Comment by tobinbradley** [comment]
I haven't seen anything like that - DB connect times I'm seeing are so fast I don't think I can measure it, even when hitting a service, deleting the database, hitting the service again, adding the database again, repeat. I'm not sure what the bottle neck you're seeing is.

I'm not shocked a compiled Go or Rust server can outrun Node in a foot race though. If you're looking for every last bit of performance, a varnish cache sitting between the server and the client would eliminate a ton of SQLite db calls.

**Comment by reyemtm** [comment]
Yeah probably my old 2 core server is the issue. Let's close this issue out
as I think the better-sqlite3 solves the initial problem.

If you're interested I have a very basic raster overzoom x2 working on my
wmts fork. Pbf and grid sources not tested.

**Comment by tobinbradley** [comment]
Marking this is closed.
