### ISSUE TITLE
Tiles access using API question

### ISSUE THREAD

**Issue by nouryf** [tobinbradley/mbtiles-server#7]
Hi,

This is not an issue, but rather a question. I was wondering if there is a way to enable access to the tiles through an API key. Only users that have valid API keys can access/fetch the vector tiles. Have you come across a Node JS app that has API key access in front of it ?

Sorry if the question is a bit generic.

Thanks

**Comment by tobinbradley** [comment]
No worries! This project uses Fastify to power the API, and Fastify has [a bunch of extensions](https://www.fastify.io/ecosystem/), including ones for various kinds of authentication. I'd pick the one that makes the most sense for your use case and give it a try.

**Comment by nouryf** [comment]
Thank you very much for the prompt response. I took a look at the suggested extensions and [fastify-api-key](https://github.com/arkerone/fastify-api-key) seems to the closest one to my use case. Thank you.
