### ISSUE TITLE
How to add MBtile Database 

### ISSUE THREAD

**Issue by GauravAshara** [tobinbradley/mbtiles-server#9]
I tried the following the URL and got an error. 

http://localhost:3000/tiles.mbtiles/12/1128/1620
{"statusCode":500,"code":"SQLITE_CANTOPEN","error":"Internal Server Error","message":"unable to open database file"}

AND list show me empty array (http://localhost:3000/list)

How I can install database ?

**Comment by tobinbradley** [comment]
By default it looks for .mbtiles files in the main project folder (where index.js is). If you want to put them in a different folder you'd need to change the tilesDir variable in index.js. 

`const tilesDir = __dirname // directory to read mbtiles files`

**Comment by GauravAshara** [comment]
Thank You for quick response 
Where can I download  .mbtiles  file ?

**Comment by tobinbradley** [comment]
No worries!

A lot of people generate their own MBTiles files, either from OpenStreetMap data or with their own data, using a variety of different tools. I personally use [tilemaker](https://tilemaker.org/). But there are some download links on [OpenStreetMap's MBTiles wiki page](https://wiki.openstreetmap.org/wiki/MBTiles), and some services like [MapTiler](https://data.maptiler.com/downloads/planet/) will sell you professionally made mbtiles files you can self host.

**Comment by GauravAshara** [comment]
Thank You Tobin Bradley, I will try above options soon.
